export type PackageData = {
    order_id: string,
    destination_name: string,
    destination_phone: string,
    destination_address: string,
    destination_kecamatan_id: bigint,
    weight: bigint,
    width: bigint,
    height: bigint,
    length: bigint,
    qty: bigint,
    item_value: bigint,
    shipping_cost: bigint,
    service: string,
    insurance_amount?: bigint,
    service_type: string,
    cod: bigint,
    package_type_id: bigint,
    item_name: string,
    drop?: boolean | false,
    note?: string | null
}
